[build]
  publish = "frontend/eeg-auth-app/dist"
  command = "cd frontend/eeg-auth-app && npm ci && npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.herokuapp.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "cd frontend/eeg-auth-app && npm run dev"
  port = 5173
  publish = "frontend/eeg-auth-app/dist"
